class SyntaxFlux:
    # Flux type
    IN_DP_E1_UBL_INVOICE = 'IN_DP_E1_UBL_INVOICE'
    IN_DP_E1_CII_16B = 'IN_DP_E1_CII_16B'
    IN_DP_E2_UBL_INVOICE_MIN = 'IN_DP_E2_UBL_INVOICE_MIN'
    IN_DP_E2_CPP_FACTURE_MIN = 'IN_DP_E2_CPP_FACTURE_MIN'
    IN_DP_E2_CII_MIN_16B = 'IN_DP_E2_CII_MIN_16B'
    IN_DP_E2_CII_FACTURX = 'IN_DP_E2_CII_FACTURX'

    IN_DP_E2_CII_MIN = 'IN_DP_E2_CII_MIN'
    IN_DP_E2_PES_FACTURE_MIN = 'IN_DP_E2_PES_FACTURE_MIN'
    IN_DP_PDFARCHIVE_UBL_INVOICE_MUG = 'IN_DP_PDFARCHIVE_UBL_INVOICE_MUG'
    IN_DP_PDFARCHIVE_CII_MUG = 'IN_DP_PDFARCHIVE_CII_MUG'
    IN_DP_E1_CII = 'IN_DP_E1_CII'
    IN_DP_E1_PES_FACTURE = 'IN_DP_E1_PES_FACTURE'
    IN_DP_E1_XCBL = 'IN_DP_E1_XCBL'